# slim syntax
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

# vim起動中に実行
[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft = ["ruby", "python", "perl"]

#入力補助
[[plugins]]
repo = 'kana/vim-smartinput'
on_i = 1
hook_post_source = '''
call smartinput#map_to_trigger('i', '<Space>', '<Space>', '<Space>')
call smartinput#define_rule({
\   'at'    : '(\%#)',
\   'char'  : '<Space>',
\   'input' : '<Space><Space><Left>',
\   })
call smartinput#define_rule({
\   'at'    : '( \%# )',
\   'char'  : '<BS>',
\   'input' : '<Del><BS>',
\   })
call smartinput#map_to_trigger('i', '#', '#', '#')

call smartinput#define_rule({
\   'at'       : '\%#',
\   'char'     : '#',
\   'input'    : '#{}<Left>',
\   'filetype' : ['ruby'],
\   'syntax'   : ['Constant', 'Special'],
\   })
call smartinput#map_to_trigger('i', '<Bar>', '<Bar>', '<Bar>')
call smartinput#define_rule({
\   'at' : '\({\|\<do\>\)\s*\%#',
\   'char' : '<Bar>',
\   'input' : '<Bar><Bar><Left>',
\   'filetype' : ['ruby'],
\    })
'''

# slim syntax
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

# toml syntax
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# jsonsyntax
[[plugins]]
repo = 'elzr/vim-json'
hook_source='let g:vim_json_syntax_conceal = 0'
on_ft = ['json']
